### ISSUE TITLE
Attend to external contributions or remove CLA and CONTRIBUTING.md

### ISSUE THREAD

**Issue by tenstad** [oracle/oracle-database-operator#102]
I highly recommend that you start developing open source in the open, instead of doing it all internally, then push one-commit releases. As of now, it appears that you do not acctually accept external contributions, which is why I feel the CLA and contribution guide indicates incorrect intensions. Having them there, you invite people to contribute, and should attend to their contributions.

However, if you want to keep it internal, I suggest that you remove the CLA and contribution guidelines. Sorry if I come of as rude, but if you only develop internally, there is no point in having a CLA and contributing guide, it's just wasting people's time.

Backstory: I previously tried to follow the process; signed the CLA and created https://github.com/oracle/oracle-database-operator/pull/78. It has now been 5 months without any action from you, before finally including the same fix in you latest release: https://github.com/oracle/oracle-database-operator/blob/31b5e9b656a5973269785ee4307d79bb9801893e/controllers/database/pdb_controller.go#L695

**Comment by mmalvezz** [comment]
Isse #78 has been closed. Please reopen #102 or #78 if there are any further technical consideration.  Regarding CLA git accounts code owner setting are fine now, there should be no more missing communication in the future.
