### ISSUE TITLE
SIDB OracleRestDataService documentation issues

### ISSUE THREAD

**Issue by andbos** [oracle/oracle-database-operator#106]
Hi,

A couple of links are broken under OracleRestDataService Resource - Template YAML and OracleRestDataService Resource - Advanced Usages - Database Actions.

https://github.com/oracle/oracle-database-operator/blob/main/docs/sidb/README.md#oraclerestdataservice-resource
https://github.com/oracle/oracle-database-operator/blob/main/docs/sidb/README.md#database-actions

Best regards,
Andreas

**Comment by IshaanDesai45** [comment]
@andbos indeed links seems to be broken will fix this

**Comment by IshaanDesai45** [comment]
@andbos Please check the above PR aimed to resolve the problem

**Comment by andbos** [comment]
Hi,

Thanks. As far as I can see these links are now working.

Best regards,
Andreas
