### ISSUE TITLE
Multitenant: new versions of ORDS (later than 23.4) dont work

### ISSUE THREAD

**Issue by ilfur** [oracle/oracle-database-operator#116]
When trying to create a new PDB , I get an error in a kubernetes event/ORDS error: "new_pdb_name is a mandatory field".
The thing is that the REST API for managing multitenant databases changed a bit with ORDS 24.1 and above.
The parameter for creating new PDBs is now called "new_pdb_name" instead of the former "pdb_name".
I suggest to use both parameters to support older and newer ORDS versions... and to check for other deprecations too :-)

**Comment by mmalvezz** [comment]
It's not just a matter of rest payload format, ords 24 is using dbms_scheduer which means implementing writing  new code paths for return code testing. We are evaluating alternative solutions
