### ISSUE TITLE
Unable to stop and start Single Instance Database

### ISSUE THREAD

**Issue by raekins** [oracle/oracle-database-operator#12]
Operator need to provide the ability to stop (normal, immediate & shutdown) and start the database 

When using the Oracle database images with a statefulset replicas can be set to 0 or 1 to stop & start, however this is not possible with the operator.

**Comment by yunus-qureshi** [comment]
This is coming in drop 2

**Comment by yunus-qureshi** [comment]
@anpanigr ETA is most likely Q1 of 2022. Till then you could exec into the pod to bounce the DB

kubectl exec -it <db pod> -- /home/oracle/shutDown.sh immediate

**Comment by yunus-qureshi** [comment]
@raekins @anpanigr drop2 is out with this enhancement
