### ISSUE TITLE
OpenShift Security Context Constraints

### ISSUE THREAD

**Issue by noxsas** [oracle/oracle-database-operator#122]
Hello,

In docs/sidb README in the section  Prerequisites there is OpenShift Security Context Constraints instructions. 
https://github.com/oracle/oracle-database-operator/tree/main/docs/sidb#openshift-security-context-constraints

My question is do I have to install OpenShift on my Linux machine ? 
I mean is it necessary ? 

I'm new here and I'm just trying to learn and I had a hard time following this whole documentation. And I just don't really understand why do I need OpenShift. I'm trying to install Oracle database on K8s. So I have my Linux machine where my Kubernetes cluster is and I also have to install OpenShift ? am I correct ?

**Comment by yunus-qureshi** [comment]
No, this is needed only if your Kubernetes distribution is OpenShift.

**Comment by noxsas** [comment]
> No, this is needed only if your Kubernetes distribution is OpenShift.

Oh okey thanks!
