### ISSUE TITLE
Operator gets "400: Invalid SNI" when accessing Ords

### ISSUE THREAD

**Issue by rbaumgar** [oracle/oracle-database-operator#126]
documentation who to create certificates is incomplete
https://github.com/oracle/oracle-database-operator/blob/main/docs/multitenant/README.md#secrets-for-certificates

operator uses the URL following URL to access ORDS: <cdb-name>-ords.<cdb-namespace>, e.g. cdb-dev-ords.oracle

that results `extfile.txt` should be created like the following example. `www.example.com` is complete useless.

`echo "subjectAltName=DNS:cdb-dev-ords,DNS:cdb-dev-ords.oracle" > extfile.txt`

**Comment by mmalvezz** [comment]
Makefile with correct example has been changed few months ago please let us know if your problem still exists  

```makefile
197         $(OPENSSL) req -newkey rsa:2048 -nodes -keyout $(SKEY) -subj "/C=US/ST=California/L=SanFrancisco/O=$(COMPANY) /CN=$(RESTPREFIX)-$(REST_SERVER).$(C    DB_NAMESPACE) /CN=$(LOCALHOST)" -out server.csr
198         $(ECHO) "subjectAltName=DNS:$(RESTPREFIX)-$(REST_SERVER).$(CDB_NAMESPACE),DNS:www.example.com" > extfile.txt
199         $(OPENSSL) x509 -req -extfile extfile.txt -days 365 -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out $(SCRT)
```

**Comment by mmalvezz** [comment]
Thank you we are going to remove the example as well please let us know if you are still facing problem 400 SNI

**Comment by rbaumgar** [comment]
I faceced the 400 SNI error again, when I exposed the ORDS service externally, than I had to create an entry with the external name.

e.g.
echo "subjectAltName=DNS:<cdbname>-ords,DNS:<cdbname>-ords.<project>,DNS:cdb-dev-ords-<project>.<openshift-domainname>" > extfile.txt
