### ISSUE TITLE
Multitenant: Usecase 3: Why is secret db-ca and db-tls created in the oprtator namespace?

### ISSUE THREAD

**Issue by rbaumgar** [oracle/oracle-database-operator#128]
$subject

https://github.com/oracle/oracle-database-operator/tree/main/docs/multitenant/usecase03

I am not able to find any reference from the operator to the secrets db-ca and db-tls.
Please clarify and document.

**Comment by mmalvezz** [comment]
We will remove line 203 and 204 from usecase03 makefile in the next few days 

```makefile
201
202 tlssecret:
203         $(KUBECTL) create secret tls db-tls --key="$(SKEY)" --cert="$(SCRT)"  -n $(CDB_NAMESPACE)
204         $(KUBECTL) create secret generic db-ca --from-file="$(CART)" -n $(CDB_NAMESPACE)

```
