### ISSUE TITLE
NetworkPolicy: managing PDB does not work

### ISSUE THREAD

**Issue by rbaumgar** [oracle/oracle-database-operator#129]
When you have a default OpenShift cluster with networkpolicies create/delete PDB does not work.
The default policies only allow traffic within the same namespace.
Managing PDBs requires that the operator sends API calls to the ORDS pod which is usually not in the same namespace as the operator.

Please update the documentation that this is a requirement and give an example.

Error: operator gets a timeout when trying to access ORDS URL.

**Comment by mmalvezz** [comment]
We have introduced multiple namespaces ... each pdb can run in a dedicated name space which is different from operator namespace and cdb namespace see docs usecases

**Comment by rbaumgar** [comment]
Yes I know. But I was not able to find any information about networkpolicies... And you have to make sure the operator is able to connect the namespace of the pdb
