### ISSUE TITLE
Failover error due to missing admin-password

### ISSUE THREAD

**Issue by raekins** [oracle/oracle-database-operator#13]
The admin-password need to persist to support failover.

For example if you create a single instance database and then kill the pod to relocate to another node the pod can start on a different node but the Operator reports an error.

**Comment by Mahi0911** [comment]
Yes, we identified it for single replica case. this is not observed in case we have multiple replicas
We will address this soon.

As, a work around, can you please try creating the admin-password secret and check if it goes through fine.

Thanks

**Comment by yunus-qureshi** [comment]
Thanks @raekins This will be fixed in drop2.  Use the workarounds suggested above

**Comment by yunus-qureshi** [comment]
@raekins drop 2 is out with this fix
