### ISSUE TITLE
Video on installation of oracle database operator and common tasks

### ISSUE THREAD

**Issue by viju2008** [oracle/oracle-database-operator#21]
Dear Sir

It would be good for the user community if a video on operator installation and a video of common tasks with the operator is created

**Comment by Kuassim** [comment]
The following [video](https://www.oracle.com/database/technologies/appdev/jdbc.html?ytid=40omFGtFe0A) shows how to perform the lifecycle of the currently supported database deployments. The installation is a single command (after the pre-requisites), but we will record a video about it.
