### ISSUE TITLE
creating and binding ADB's

### ISSUE THREAD

**Issue by mnemonic01** [oracle/oracle-database-operator#25]
Hi
Is creating and binding ADB's already working? As for the OCI operator, one has to install the SDK with OLM, I don't see this coming back here

Thanks

**Comment by harayuanwang** [comment]
Yes, creating and binding ADBs are supported in OraOperator. Please refer to the docs for more details: [https://github.com/oracle/oracle-database-operator/blob/main/docs/adb/README.md#supported-features](https://github.com/oracle/oracle-database-operator/blob/main/docs/adb/README.md#supported-features).

**Comment by ting-lan-wang** [comment]
Closing this issue as the question is inactivated for more than a year.
