### ISSUE TITLE
Include a link to the hands-on lab on the Containerized Single Instance use-case

### ISSUE THREAD

**Issue by janleemans** [oracle/oracle-database-operator#29]
A [lab is now available](https://oracle.github.io/cloudtestdrive/AppDev/database-operator/workshops/freetier/?lab=introduction) in the LiveLab format with detailed instructions to run the Containerized Single Instance database on an OCI trial account, using both dynamic block storage and NFS storage.
It might be interesting to include a link to this lab in the documentation.

**Comment by yunus-qureshi** [comment]
@janleemans this is really good. Thanks will include the link.

**Comment by abhisbyk** [comment]
@janleemans Addressed this in PR #30. Closing this issue.
