### ISSUE TITLE
Unable to set resources for Single Instance Database

### ISSUE THREAD

**Issue by wdonne** [oracle/oracle-database-operator#51]
Hello,

When creating such a database it is not possible to set the `resources` property in the spec. When the pod starts it complains about needing at least 2GB of memory (Express edition), but it got only 512MB. This was probably all that remained on the node it was scheduled to. With the `resources` property the scheduler could be forced to select a proper node.

Best regards,

Werner.

**Comment by IshaanDesai45** [comment]
Hey, 
just to confirm, so the problem here is that today with the sidb CR we are not able to set the resources i.e the memory or cpu needed by the CR. And as a result its getting scheduled on nodes with low resources ?

**Comment by IshaanDesai45** [comment]
@wdonne 
We currently don't support resource based scheduling for the sidb pods.This might get in the next release. Till then please use the nodeSelector property with proper selector labels to achieve this.

**Comment by yunus-qureshi** [comment]
## Deploy only on nodes having required labels. Format label_name: label_value
  ## For instance if the pods need to be restricted to a particular AD
  ## Leave commented if there is no such requirement.
  # nodeSelector:
  #   topology.kubernetes.io/zone: PHX-AD-1
