### ISSUE TITLE
Enterprise SIDB Provisioning Fails on getting Oracle Base

### ISSUE THREAD

**Issue by Graya25** [oracle/oracle-database-operator#57]
When deploying a SIDB using an Oracle 19c or 21c image from Oracle's container registry and the 0.2.1 version of the operator, we are getting errors upon startup of the database using the operator.

21c image:
```
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
Prepare for db operation
8% complete
Copying database files
9% complete
[WARNING] ORA-09925: Unable to create audit trail file

[FATAL] ORA-01034: ORACLE not available

31% complete
100% complete
[FATAL] ORA-01034: ORACLE not available

8% complete
0% complete
Look at the log file "/home/oracle/Cannot obtain the oracle base/cfgtoollogs/dbca/ENT123/ENT123.log" for further details.
cat: /opt/oracle/cfgtoollogs/dbca/ENT123/ENT123.log: No such file or directory
cat: /opt/oracle/cfgtoollogs/dbca/ENT123.log: No such file or directory
```

19c image
```
Listening Endpoints Summary...
(DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
PRCR-1159 : Failed to create file output stream because of empty file name
PRCR-1159 : Failed to create file output stream because of empty file name
[FATAL] [DBT-06604] The location specified for 'Data Files Location' has insufficient free space.
CAUSE: Only (0MB) free space is available on the location (?g3?/oradata/ENT123).
ACTION: Choose a 'Data Files Location' that has enough space (minimum of (3,603MB)) or free up space on the specified location.
cat: /opt/oracle/cfgtoollogs/dbca/ENT123/ENT123.log: No such file or directory
cat: /opt/oracle/cfgtoollogs/dbca/ENT123.log: No such file or directory 
```

In either case, it seems like the ORACLE_BASE value isn't being retrieved properly from the Oracle provided image. Both test cases run in TKG clusters on vSphere with Tanzu 7 on Kubernetes 1.21. A 100GB PV is successfully provisioned for both and bound via a PVC successfully but is unutilized due to the missing ORACLE_BASE value.
Both images are provided from:
registry.oracle.com/database/enterprise:latest
registry.oracle.com/database/enterprise:19.3.0.0

**Comment by yunus-qureshi** [comment]
DB creation failure is the main issue here that is causing the other issues. 
It seems your PV does not have sufficient space. Look at this

[FATAL] [DBT-06604] The location specified for 'Data Files Location' has insufficient free space.
CAUSE: Only (0MB) free space is available on the location (?g3?/oradata/ENT123).
ACTION: Choose a 'Data Files Location' that has enough space (minimum of (3,603MB)) or free up space on the specified location.

And it may it does not write permissions too 
[WARNING] ORA-09925: Unable to create audit trail file

**Comment by IshaanDesai45** [comment]
@Graya25 I am closing this issue. If you are still facing this error after clearing up space in the PV please reopen the issue then.
