### ISSUE TITLE
Error from server (InternalError): error when creating "oracle-database-operator.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": context deadline exceeded

### ISSUE THREAD

**Issue by dadde-oracle** [oracle/oracle-database-operator#80]
I use the process from here: https://ronekins.com/2021/11/11/getting-started-with-the-oracle-database-kubernetes-operator-part-1/ or here: https://github.com/oracle/oracle-database-operator

1. Verify install of Cert-Manager

`# kubectl get pods --namespace cert-manager
`

> NAME                                       READY   STATUS    RESTARTS   AGE
> cert-manager-5f68c9c6dd-9h49r              1/1     Running   0          66s
> cert-manager-cainjector-57d6fc9f7d-58fjn   1/1     Running   0          66s
> cert-manager-webhook-5b7ffbdc98-gx72v      1/1     Running   0          66s
> 

2. Install the operator from github

`# kubectl apply -f https://raw.githubusercontent.com/oracle/oracle-database-operator/main/oracle-database-operator.yaml
`

> namespace/oracle-database-operator-system created
> customresourcedefinition.apiextensions.k8s.io/autonomouscontainerdatabases.database.oracle.com created
> customresourcedefinition.apiextensions.k8s.io/autonomousdatabasebackups.database.oracle.com created
> customresourcedefinition.apiextensions.k8s.io/autonomousdatabaserestores.database.oracle.com created
> customresourcedefinition.apiextensions.k8s.io/autonomousdatabases.database.oracle.com created
> customresourcedefinition.apiextensions.k8s.io/cdbs.database.oracle.com created
> customresourcedefinition.apiextensions.k8s.io/dataguardbrokers.database.oracle.com created
> customresourcedefinition.apiextensions.k8s.io/dbcssystems.database.oracle.com created
> customresourcedefinition.apiextensions.k8s.io/oraclerestdataservices.database.oracle.com created
> customresourcedefinition.apiextensions.k8s.io/pdbs.database.oracle.com created
> customresourcedefinition.apiextensions.k8s.io/shardingdatabases.database.oracle.com created
> customresourcedefinition.apiextensions.k8s.io/singleinstancedatabases.database.oracle.com created
> role.rbac.authorization.k8s.io/oracle-database-operator-leader-election-role created
> clusterrole.rbac.authorization.k8s.io/oracle-database-operator-manager-role created
> clusterrole.rbac.authorization.k8s.io/oracle-database-operator-metrics-reader created
> clusterrole.rbac.authorization.k8s.io/oracle-database-operator-oracle-database-operator-proxy-role created
> rolebinding.rbac.authorization.k8s.io/oracle-database-operator-oracle-database-operator-leader-election-rolebinding created
> clusterrolebinding.rbac.authorization.k8s.io/oracle-database-operator-oracle-database-operator-manager-rolebinding created
> clusterrolebinding.rbac.authorization.k8s.io/oracle-database-operator-oracle-database-operator-proxy-rolebinding created
> service/oracle-database-operator-controller-manager-metrics-service created
> service/oracle-database-operator-webhook-service created
> mutatingwebhookconfiguration.admissionregistration.k8s.io/oracle-database-operator-mutating-webhook-configuration created
> validatingwebhookconfiguration.admissionregistration.k8s.io/oracle-database-operator-validating-webhook-configuration created
> deployment.apps/oracle-database-operator-controller-manager created
> Error from server (InternalError): error when creating "https://raw.githubusercontent.com/oracle/oracle-database-operator/main/oracle-database-operator.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": context deadline exceeded
> Error from server (InternalError): error when creating "https://raw.githubusercontent.com/oracle/oracle-database-operator/main/oracle-database-operator.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s": context deadline exceeded
> 

3. Checking the dns is running (coredns and flannel)

# kubectl get pods -n kube-system

> NAME                                       READY   STATUS    RESTARTS   AGE
> coredns-dcb45f57-hzqbn                     1/1     Running   5          10d
> coredns-dcb45f57-ndxqh                     1/1     Running   5          10d
> etcd-verrazzano-api-2                      1/1     Running   5          10d
> kube-apiserver-verrazzano-api-2            1/1     Running   5          10d
> kube-controller-manager-verrazzano-api-2   1/1     Running   5          10d
> kube-flannel-ds-dqcqk                      1/1     Running   5          10d
> kube-flannel-ds-mc7vz                      1/1     Running   6          10d
> kube-flannel-ds-xl4q6                      1/1     Running   7          10d
> kube-proxy-2ff8c                           1/1     Running   5          10d
> kube-proxy-9fjvm                           1/1     Running   5          10d
> kube-proxy-m6qrj                           1/1     Running   5          10d
> kube-scheduler-verrazzano-api-2            1/1     Running   5          10d

4. Firewall is stopped for this install

`# systemctl status firewalld
`

> ● firewalld.service - firewalld - dynamic firewall daemon
>    Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
>    Active: inactive (dead) since Wed 2024-01-17 07:19:10 GMT; 8s ago
>      Docs: man:firewalld(1)
>   Process: 1474 ExecStart=/usr/sbin/firewalld --nofork --nopid $FIREWALLD_ARGS (code=exited, status=0/SUCCESS)
>  Main PID: 1474 (code=exited, status=0/SUCCESS)
> 
> Jan 17 06:41:16 verrazzano-api-2 systemd[1]: Starting firewalld - dynamic firewall daemon...
> Jan 17 06:41:16 verrazzano-api-2 systemd[1]: Started firewalld - dynamic firewall daemon.
> Jan 17 06:41:16 verrazzano-api-2 firewalld[1474]: WARNING: AllowZoneDrifting is enabled. This is considered an insecure configuration option. It will be removed in a future release>
> Jan 17 07:19:10 verrazzano-api-2 systemd[1]: Stopping firewalld - dynamic firewall daemon...
> Jan 17 07:19:10 verrazzano-api-2 systemd[1]: firewalld.service: Succeeded.
> Jan 17 07:19:10 verrazzano-api-2 systemd[1]: Stopped firewalld - dynamic firewall daemon.
> > 

5. egress and ingress rules

> Egress: 0.0.0.0/0	TCP	All	All		
> Ingress: 10.0.2.0/24	TCP	All	All
> 

What to check and install the operator?

**Comment by dadde-oracle** [comment]
Hello ishaan

Thanks for helping, here are details.

Kubernetes is installed according to the OCNE documentation.

Machines are running as VM on OCI in Frankfurt.
***@***.***

A single Subnet for all
***@***.***

And the security rules
***@***.***


All for VM have SE disabled

***@***.*** ~]#
sestatus
SELinux status:                 disabled

Linux Firewall is disabled too for all 4 VMs
***@***.*** ~]#
systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:firewalld(1)

Kubernetes version
***@***.*** ~]#
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.10+2.el8", GitCommit:"a22a61e842e309e518df8edf27afee0caaa1cdf8", GitTreeState:"clean", BuildDate:"2023-12-18T14:40:09Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.10+2.el8", GitCommit:"a22a61e842e309e518df8edf27afee0caaa1cdf8", GitTreeState:"clean", BuildDate:"2023-12-18T14:49:13Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}

***@***.*** ~]#
kubectl get nodes -o wide
NAME               STATUS   ROLES           AGE   VERSION          INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                  KERNEL-VERSION                      CONTAINER-RUNTIME
verrazzano-api-2   Ready    control-plane   12d   v1.26.10+2.el8   10.0.2.253    <none>        Oracle Linux Server 8.9   5.15.0-202.135.2.el8uek.x86_64      cri-o://1.26.3
verrazzano-wrk-3   Ready    <none>          12d   v1.26.10+2.el8   10.0.2.185    <none>        Oracle Linux Server 8.8   5.15.0-200.131.27.1.el8uek.x86_64   cri-o://1.26.3
verrazzano-wrk-4   Ready    <none>          12d   v1.26.10+2.el8   10.0.2.56     <none>        Oracle Linux Server 8.8   5.15.0-200.131.27.1.el8uek.x86_64   cri-o://1.26.3

Install the cer-manager

kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.yaml
namespace/cert-manager created
customresourcedefinition.apiextensions.k8s.io/certificaterequests.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/certificates.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/challenges.acme.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/clusterissuers.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/issuers.cert-manager.io created
customresourcedefinition.apiextensions.k8s.io/orders.acme.cert-manager.io created
serviceaccount/cert-manager-cainjector created
serviceaccount/cert-manager created
serviceaccount/cert-manager-webhook created
configmap/cert-manager-webhook created
clusterrole.rbac.authorization.k8s.io/cert-manager-cainjector created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-issuers created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-certificates created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-orders created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-challenges created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim created
clusterrole.rbac.authorization.k8s.io/cert-manager-view created
clusterrole.rbac.authorization.k8s.io/cert-manager-edit created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-approve:cert-manager-io created
clusterrole.rbac.authorization.k8s.io/cert-manager-controller-certificatesigningrequests created
clusterrole.rbac.authorization.k8s.io/cert-manager-webhook:subjectaccessreviews created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-cainjector created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-issuers created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-clusterissuers created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-certificates created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-orders created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-challenges created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-ingress-shim created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-approve:cert-manager-io created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-controller-certificatesigningrequests created
clusterrolebinding.rbac.authorization.k8s.io/cert-manager-webhook:subjectaccessreviews created
role.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection created
role.rbac.authorization.k8s.io/cert-manager:leaderelection created
role.rbac.authorization.k8s.io/cert-manager-webhook:dynamic-serving created
rolebinding.rbac.authorization.k8s.io/cert-manager-cainjector:leaderelection created
rolebinding.rbac.authorization.k8s.io/cert-manager:leaderelection created
rolebinding.rbac.authorization.k8s.io/cert-manager-webhook:dynamic-serving created
service/cert-manager created
service/cert-manager-webhook created
deployment.apps/cert-manager-cainjector created
deployment.apps/cert-manager created
deployment.apps/cert-manager-webhook created
mutatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created
validatingwebhookconfiguration.admissionregistration.k8s.io/cert-manager-webhook created

Wiat some time (10 minutes)
kubectl get pods --namespace cert-manager
NAME                                       READY   STATUS    RESTARTS   AGE
cert-manager-5f68c9c6dd-ttlxl              1/1     Running   0          88s
cert-manager-cainjector-57d6fc9f7d-jncr2   1/1     Running   0          88s
cert-manager-webhook-5b7ffbdc98-qhmsd      1/1     Running   0          88s

kubectl get pods --namespace cert-manager
NAME                                       READY   STATUS    RESTARTS   AGE
cert-manager-5f68c9c6dd-ttlxl              1/1     Running   0          10m
cert-manager-cainjector-57d6fc9f7d-jncr2   1/1     Running   0          10m
cert-manager-webhook-5b7ffbdc98-qhmsd      1/1     Running   0          10m

Setup the database operator
kubectl apply -f https://raw.githubusercontent.com/oracle/oracle-database-operator/main/oracle-database-operator.yaml
namespace/oracle-database-operator-system created
customresourcedefinition.apiextensions.k8s.io/autonomouscontainerdatabases.database.oracle.com created
customresourcedefinition.apiextensions.k8s.io/autonomousdatabasebackups.database.oracle.com created
customresourcedefinition.apiextensions.k8s.io/autonomousdatabaserestores.database.oracle.com created
customresourcedefinition.apiextensions.k8s.io/autonomousdatabases.database.oracle.com created
customresourcedefinition.apiextensions.k8s.io/cdbs.database.oracle.com created
customresourcedefinition.apiextensions.k8s.io/dataguardbrokers.database.oracle.com created
customresourcedefinition.apiextensions.k8s.io/dbcssystems.database.oracle.com created
customresourcedefinition.apiextensions.k8s.io/oraclerestdataservices.database.oracle.com created
customresourcedefinition.apiextensions.k8s.io/pdbs.database.oracle.com created
customresourcedefinition.apiextensions.k8s.io/shardingdatabases.database.oracle.com created
customresourcedefinition.apiextensions.k8s.io/singleinstancedatabases.database.oracle.com created
role.rbac.authorization.k8s.io/oracle-database-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/oracle-database-operator-manager-role created
clusterrole.rbac.authorization.k8s.io/oracle-database-operator-metrics-reader created
clusterrole.rbac.authorization.k8s.io/oracle-database-operator-oracle-database-operator-proxy-role created
rolebinding.rbac.authorization.k8s.io/oracle-database-operator-oracle-database-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/oracle-database-operator-oracle-database-operator-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/oracle-database-operator-oracle-database-operator-proxy-rolebinding created
service/oracle-database-operator-controller-manager-metrics-service created
service/oracle-database-operator-webhook-service created
mutatingwebhookconfiguration.admissionregistration.k8s.io/oracle-database-operator-mutating-webhook-configuration created
validatingwebhookconfiguration.admissionregistration.k8s.io/oracle-database-operator-validating-webhook-configuration created
deployment.apps/oracle-database-operator-controller-manager created
Error from server (InternalError): error when creating https://raw.githubusercontent.com/oracle/oracle-database-operator/main/oracle-database-operator.yaml: Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s: context deadline exceeded
Error from server (InternalError): error when creating https://raw.githubusercontent.com/oracle/oracle-database-operator/main/oracle-database-operator.yaml: Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s: context deadline exceeded

Same error
Error from server (InternalError): error when creating https://raw.githubusercontent.com/oracle/oracle-database-operator/main/oracle-database-operator.yaml: Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s: context deadline exceeded
Error from server (InternalError): error when creating https://raw.githubusercontent.com/oracle/oracle-database-operator/main/oracle-database-operator.yaml: Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s: context deadline exceeded


What do you think?

Thanks
David

De : Ishaan Desai ***@***.***>
Date : jeudi, 18 janvier 2024 à 09:32
À : oracle/oracle-database-operator ***@***.***>
Cc : DAVID ADDE ***@***.***>, Author ***@***.***>
Objet : [External] : Re: [oracle/oracle-database-operator] Error from server (InternalError): error when creating "oracle-database-operator.yaml": Internal error occurred: failed calling webhook "webhook.cert-manager.io": failed to call webhook: Post "https://...

Hi david, you seem to have all the conditions met. Can you just retry once; also share you environment details

**Comment by yunus-qureshi** [comment]
helm install of cert-manager did the trick

helm install   cert-manager jetstack/cert-manager   --namespace cert-manager   --create-namespace   --version v1.13.3 --set installCRDs=true --set webhook.hostNetwork=true --set webhook.securePort=10260
